ALTER TABLE subscribers    NO FORCE ROW LEVEL SECURITY;
ALTER TABLE suppressions   NO FORCE ROW LEVEL SECURITY;
ALTER TABLE preferences    NO FORCE ROW LEVEL SECURITY;
ALTER TABLE consent_ledger NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs     NO FORCE ROW LEVEL SECURITY;
