/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppTemplatesTemplateIdRouteImport } from './routes/_app/templates.$templateId'
import { Route as AppWorkflowsRouteImport } from './routes/_app/workflows'
import { Route as AppWorkflowsWorkflowIdRouteImport } from './routes/_app/workflows.$workflowId'
import { Route as AppSubscribersRouteImport } from './routes/_app/subscribers'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppSettingsProvidersRouteImport } from './routes/_app/settings/providers'
import { Route as AppSettingsDltRouteImport } from './routes/_app/settings/dlt'
import { Route as AppSettingsApiKeysRouteImport } from './routes/_app/settings/api-keys'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)

const AppTemplatesTemplateIdRoute = AppTemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => AppRoute,
} as any)

const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)

const AppWorkflowsWorkflowIdRoute = AppWorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => AppRoute,
} as any)

const AppSubscribersRoute = AppSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AppRoute,
} as any)

const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsProvidersRoute = AppSettingsProvidersRouteImport.update({
  id: '/settings/providers',
  path: '/settings/providers',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsDltRoute = AppSettingsDltRouteImport.update({
  id: '/settings/dlt',
  path: '/settings/dlt',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => AppRoute,
} as any)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppTemplatesTemplateIdRoute: typeof AppTemplatesTemplateIdRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppWorkflowsWorkflowIdRoute: typeof AppWorkflowsWorkflowIdRoute
  AppSubscribersRoute: typeof AppSubscribersRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppSettingsProvidersRoute: typeof AppSettingsProvidersRoute
  AppSettingsDltRoute: typeof AppSettingsDltRoute
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppTemplatesTemplateIdRoute: AppTemplatesTemplateIdRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppWorkflowsWorkflowIdRoute: AppWorkflowsWorkflowIdRoute,
  AppSubscribersRoute: AppSubscribersRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppLogsRoute: AppLogsRoute,
  AppSettingsProvidersRoute: AppSettingsProvidersRoute,
  AppSettingsDltRoute: AppSettingsDltRoute,
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/templates'
    | '/templates/$templateId'
    | '/workflows'
    | '/workflows/$workflowId'
    | '/subscribers'
    | '/analytics'
    | '/logs'
    | '/settings/providers'
    | '/settings/dlt'
    | '/settings/api-keys'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/templates'
    | '/templates/$templateId'
    | '/workflows'
    | '/workflows/$workflowId'
    | '/subscribers'
    | '/analytics'
    | '/logs'
    | '/settings/providers'
    | '/settings/dlt'
    | '/settings/api-keys'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/'
    | '/_app/templates'
    | '/_app/templates/$templateId'
    | '/_app/workflows'
    | '/_app/workflows/$workflowId'
    | '/_app/subscribers'
    | '/_app/analytics'
    | '/_app/logs'
    | '/_app/settings/providers'
    | '/_app/settings/dlt'
    | '/_app/settings/api-keys'
  fileRoutesById: FileRoutesById
}

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/templates': typeof AppTemplatesRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/workflows': typeof AppWorkflowsRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/subscribers': typeof AppSubscribersRoute
  '/analytics': typeof AppAnalyticsRoute
  '/logs': typeof AppLogsRoute
  '/settings/providers': typeof AppSettingsProvidersRoute
  '/settings/dlt': typeof AppSettingsDltRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/templates': typeof AppTemplatesRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/workflows': typeof AppWorkflowsRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/subscribers': typeof AppSubscribersRoute
  '/analytics': typeof AppAnalyticsRoute
  '/logs': typeof AppLogsRoute
  '/settings/providers': typeof AppSettingsProvidersRoute
  '/settings/dlt': typeof AppSettingsDltRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/': typeof AppIndexRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/_app/workflows': typeof AppWorkflowsRoute
  '/_app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/_app/subscribers': typeof AppSubscribersRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/settings/providers': typeof AppSettingsProvidersRoute
  '/_app/settings/dlt': typeof AppSettingsDltRoute
  '/_app/settings/api-keys': typeof AppSettingsApiKeysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/$templateId': {
      id: '/_app/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AppTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/$workflowId': {
      id: '/_app/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscribers': {
      id: '/_app/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof AppSubscribersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/providers': {
      id: '/_app/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof AppSettingsProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/dlt': {
      id: '/_app/settings/dlt'
      path: '/settings/dlt'
      fullPath: '/settings/dlt'
      preLoaderRoute: typeof AppSettingsDltRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
