apiVersion: v1
kind: Service
metadata:
  name: qeet-notify-api
  namespace: qeet-notify
spec:
  selector:
    app: qeet-notify-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: sse
      port: 8082
      targetPort: 8082
