apiVersion: apps/v1
kind: Deployment
metadata:
  name: qeet-notify-workflow
  namespace: qeet-notify
  labels:
    app: qeet-notify-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qeet-notify-workflow
  template:
    metadata:
      labels:
        app: qeet-notify-workflow
    spec:
      containers:
        - name: workflow
          image: ghcr.io/qeetgroup/qeet-notify-workflow:latest
          envFrom:
            - configMapRef:
                name: qeet-notify-config
            - secretRef:
                name: qeet-notify-secrets
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
